language: julia

sudo: false

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

after_success:
- julia -e 'cd(Pkg.dir("Base58")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
